name: Simple PHP CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate PHP version
      run: php -v

    - name: Install Composer (if needed)
      run: |
        if [ -f "composer.json" ]; then
          composer install --prefer-dist --no-progress --no-suggest
        fi

    - name: Validate PHP syntax
      run: |
        find . -name "*.php" -print0 | xargs -0 -n 1 php -l

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.ref == 'refs/heads/main' && success()

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      uses: webfactory/ssh-agent@v0.5.4
      with:
        ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

    - name: Deploy to EC2
      run: |
        rsync -avz --exclude='.git*' --exclude='node_modules' --exclude='.github' ./ ec2-user@your-ec2-public-dns:/var/www/html/your-app-directory
        ssh ec2-user@your-ec2-public-dns << 'EOF'
          cd /var/www/html/your-app-directory
          composer install --prefer-dist --no-progress --no-suggest
          php artisan migrate --force
          php artisan cache:clear
          php artisan config:cache
          sudo systemctl restart apache2  # or nginx if you're using nginx
        EOF
