name: Simple PHP CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.2'

    - name: Validate PHP version
      run: php -v

    - name: Install Composer dependencies
      if: fileExists('composer.json')
      run: composer install --prefer-dist --no-progress --no-suggest

    - name: Validate PHP syntax
      run: |
        for file in $(find . -name "*.php"); do
          php -l $file;
        done
